### ISSUE TITLE
Internal delays

### ISSUE THREAD

**Issue by neveritt** [KTH-AC/ControlCore.jl#17]
We should keep track of the internal time delays. 

It is a nice feature and necessary when we are relying on `Polynomials` which trims away any zero leading coefficients...

**Comment by aytekinar** [comment]
how about the continuous-time systems, then? shall we keep track of the delays explicitly in them, also, or is it just in the discrete-time systems?

**Comment by neveritt** [comment]
I guess we should have a look at the two papers [1] and [2] referenced by [Matlab](http://se.mathworks.com/help/control/ug/internal-delays.html). 

It seems that it would be simply generalizations of the types that we have implemented, with one system without delays interconnected with a diagonal system containing the delays. 

For the discrete trational types we just need to keep the DSP representation internally.

- [1] P. Gahinet and L.F. Shampine, "Software for Modeling and Analysis of Linear Systems with Delays," Proc. American Control Conf., Boston, 2004, pp. 5600-5605

- [2] L.F. Shampine and P. Gahinet, Delay-differential-algebraic Equations in Control Theory, Applied Numerical Mathematics, 56 (2006), pp. 574-588

**Comment by neveritt** [comment]
I will leave the internal time delays for future work.
